name: Create Diagram

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

      - name: Generate constant diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output: ./diagram.svg # Генерация диаграммы с постоянным названием

      - name: Generate timestamped diagram
        run: |
          mkdir -p diagrams
          cp ./diagram.svg ./diagrams/diagram-$(date +'%Y%m%d%H%M%S').svg

      - name: Commit and push diagrams
        run: |
          git add ./diagram.svg
          git add ./diagrams/diagram-*.svg
          git diff --cached --quiet || git commit -m "Update repository diagram and save versioned copy"
          git push
