name: Save Repository Diagram

on:
  push:
    branches:
      - main

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.9.1

      - name: Save diagram with timestamp
        run: |
          mkdir -p diagrams
          mv diagram.svg diagrams/diagram-$(date +'%Y%m%d%H%M%S').svg

      - name: Commit and push diagrams
        run: |
          git add diagrams/
          git commit -m "Add new diagram"
          git push
